# Generated by Django 2.2.7 on 2019-12-23 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_auto_20191223_1133'),
        ('home', '0011_auto_20191223_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('astatus', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=15)),
                ('cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Companyregistration')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Vacancy')),
            ],
        ),
    ]
