# Generated by Django 2.2.7 on 2019-12-23 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Companyregistration'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 23, 8, 20, 28, 154017, tzinfo=utc)),
        ),
    ]
