# Generated by Django 2.2.7 on 2019-12-23 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20191223_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Companyregistration'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
