# Generated by Django 2.2.7 on 2019-12-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20191223_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='experience',
        ),
        migrations.AlterField(
            model_name='apply',
            name='cand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Companyregistration'),
        ),
    ]
