# Generated by Django 2.2.7 on 2019-12-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0010_auto_20191218_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=15)),
                ('keyskills', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('lastdate', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('vacstatus', models.IntegerField()),
                ('cmpreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Login')),
            ],
        ),
    ]
