# Generated by Django 2.2.7 on 2019-12-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191218_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='log',
            new_name='loginkey',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cmpreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Candidatereg'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='loginkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Login'),
        ),
    ]
