# Generated by Django 2.2.7 on 2019-12-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191218_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='loginkey',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cmpreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Companyregistration'),
        ),
    ]
